#!/bin/sh
# mkkit.sh — wrap tk9wm as a STARKIT and as a STARPACK.
#
# The window manager, its shim and treectrl in one file, running on a
# stock tclkit rather than on a whale: a kit is what a machine with no
# whale (and no toolchain) can be handed.
#
#   ./kit/so.sh                     the binary parts (see there)
#   TCLKIT=…/tclkit-9.0.4-Linux64-intel-tk SDX=…/sdx.kit ./kit/mkkit.sh
#
#   kit/tk9wm.kit   starkit  — needs a tclkit: `tclkit tk9wm.kit`
#   kit/tk9wm.bin   starpack — needs nothing:  `./tk9wm.bin`
#
# TCLKIT is both the runtime the starpack is built on and the
# interpreter sdx runs under; SDX is sdx.kit. Neither has a default:
# where a kit distribution lives is the builder's business.
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/.." && pwd)
SO=${SO:-$HERE/so}
for v in TCLKIT SDX; do
    eval "val=\$$v"
    if [ -z "$val" ] || [ ! -f "$val" ]; then
	echo "mkkit.sh: set $v to an existing file (tclkit runtime / sdx.kit)" >&2
	exit 2
    fi
done
if [ ! -f "$SO/libtkwmx.so" ] || [ ! -d "$SO/treectrl" ]; then
    echo "mkkit.sh: no binary parts in $SO — run ./kit/so.sh first" >&2
    exit 2
fi

VFS=$HERE/tk9wm.vfs
rm -rf "$VFS"
mkdir -p "$VFS/lib/tk9wm" "$VFS/lib/tkwmx"

# the window manager itself — the package, exactly as `make
# install-library` would lay it out
for f in substrate.tcl policy.tcl main.tcl default-config.tcl pkgIndex.tcl; do
    cp "$ROOT/library/$f" "$VFS/lib/tk9wm/"
done

# the shim, with the index `make install-shim` would have written
cp "$SO/libtkwmx.so" "$VFS/lib/tkwmx/"
cat > "$VFS/lib/tkwmx/pkgIndex.tcl" <<'EOF'
# generated by kit/mkkit.sh
package ifneeded tkwmx 0.1 \
    [list load [file join $dir libtkwmx.so] Tkwmx]
EOF

# treectrl, as whalebuild's `so` command laid it out, index included
cp -a "$SO/treectrl" "$VFS/lib/"

# The kit's entry point. Loading a shared library out of a starkit's
# VFS is the core's business and not ours: Tcl copies it to a temporary
# file and loads that, which is why a .so inside a kit works at all.
cat > "$VFS/main.tcl" <<'EOF'
# tk9wm as a starkit / starpack: the window manager, its shim and
# treectrl in one file. starkit::startup mounts us and puts our lib/ on
# auto_path; everything after that is the ordinary entry point.
package require starkit
if {[starkit::startup] eq "sourced"} return
package require tk9wm
tk9wm-main {*}$argv
EOF

# sdx refuses to use as a prefix the runtime it is itself running from,
# so the starpack is built on a COPY — which also cuts the result loose
# from wherever the stock tclkit happens to live.
cp -f "$TCLKIT" "$HERE/runtime-tclkit"
chmod +w "$HERE/runtime-tclkit"

cd "$HERE"
rm -f tk9wm.kit tk9wm.bin
"$TCLKIT" "$SDX" wrap tk9wm.kit -vfs tk9wm.vfs
"$TCLKIT" "$SDX" wrap tk9wm.bin -vfs tk9wm.vfs -runtime "$HERE/runtime-tclkit"
chmod +x tk9wm.kit tk9wm.bin
ls -l tk9wm.kit tk9wm.bin
