#!/bin/sh
# mkkit.sh — wrap tk9wm as a STARKIT and as a STARPACK.
#
# The window manager, its shim and treectrl in one file, running on a
# stock tclkit rather than on a whale: a kit is what a machine with no
# whale (and no toolchain) can be handed.
#
#   ./kit/so.sh                     the binary parts (see there)
#   TCLKIT=…/tclkit-9.0.4-Linux64-intel-tk SDX=…/sdx.kit ./kit/mkkit.sh
#
#   kit/tk9wm.kit   starkit  — needs a tclkit: `tclkit tk9wm.kit`
#   kit/tk9wm.bin   starpack — needs nothing:  `./tk9wm.bin`
#
# TCLKIT is both the runtime the starpack is built on and the
# interpreter sdx runs under; SDX is sdx.kit. Neither has a default:
# where a kit distribution lives is the builder's business.
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/.." && pwd)
SO=${SO:-$HERE/so}
for v in TCLKIT SDX; do
    eval "val=\$$v"
    if [ -z "$val" ] || [ ! -f "$val" ]; then
	echo "mkkit.sh: set $v to an existing file (tclkit runtime / sdx.kit)" >&2
	exit 2
    fi
done
if [ ! -f "$SO/libtkwmx.so" ] || [ ! -d "$SO/treectrl" ] \
	|| [ ! -f "$SO/libtcl9tk9.0.so" ] || [ ! -d "$SO/tk9.0" ]; then
    echo "mkkit.sh: no binary parts in $SO — run ./kit/so.sh first" >&2
    exit 2
fi

VFS=$HERE/tk9wm.vfs
rm -rf "$VFS"
mkdir -p "$VFS/lib/tk9wm" "$VFS/lib/tkwmx"

# the window manager itself — the library WHOLE, because a curated
# list is a manifest nobody maintains: the one that stood here rotted
# the moment the library grew (fut.tcl, treesync.tcl, the widgets —
# pkgIndex.tcl sources them unconditionally, so a kit built off the
# old list died on its first breath; the ui host and the .el templates
# are read off the library at run time and were missing too). The
# directory itself is the manifest, and it cannot fall behind.
cp -a "$ROOT/library/." "$VFS/lib/tk9wm/"

# the shim, with the index `make install-shim` would have written
cp "$SO/libtkwmx.so" "$VFS/lib/tkwmx/"
cat > "$VFS/lib/tkwmx/pkgIndex.tcl" <<'EOF'
# generated by kit/mkkit.sh
package ifneeded tkwmx 0.1 \
    [list load [file join $dir libtkwmx.so] Tkwmx]
EOF

# treectrl, as whalebuild's `so` command laid it out, index included
cp -a "$SO/treectrl" "$VFS/lib/"

# Tk — our own shared Xft build: the .so and its script library in one
# package directory. The index makes lib/tk9.0 normal for whoever else
# asks; the kit itself does not wait for it — main.tcl loads Tk by
# hand, first thing, because on a tclkit with a built-in static Tk the
# require would be won by the boot-registered ifneeded, not by any
# pkgIndex on auto_path.
cp -a "$SO/tk9.0" "$VFS/lib/tk9.0"
cp "$SO/libtcl9tk9.0.so" "$VFS/lib/tk9.0/"
cat > "$VFS/lib/tk9.0/pkgIndex.tcl" <<'EOF'
# generated by kit/mkkit.sh
package ifneeded tk 9.0.4 [list load [file join $dir libtcl9tk9.0.so]]
package ifneeded Tk 9.0.4 [list package require -exact tk 9.0.4]
EOF

# The kit's entry point. Loading a shared library out of a starkit's
# VFS is the core's business and not ours: Tcl copies it to a temporary
# file and loads that, which is why a .so inside a kit works at all.
cat > "$VFS/main.tcl" <<'EOF'
# tk9wm as a starkit / starpack: the window manager, its shim and
# treectrl in one file. starkit::startup mounts us and puts our lib/ on
# auto_path; everything after that is the ordinary entry point.
package require starkit
set mode [starkit::startup]
if {$mode eq "sourced"} return
# How to become us again after a restart in place — asked of starkit
# rather than inferred, since it is the one that knows: a STARPACK is
# its own application and takes no script argument, while a STARKIT is
# a file its interpreter has to be told about again (which is what
# makes replacing the .kit and restarting come up on the new one). The
# substrate can guess both, and does when nobody tells it; a wrapper
# that knows should not leave it guessing.
switch -- $mode {
    starpack { set ::tk9wm_reexec [list [info nameofexecutable]] }
    starkit  { set ::tk9wm_reexec [list [info nameofexecutable] \
                                        $::starkit::topdir] }
}
# Tk rides in the kit: our own Xft-enabled shared build, loaded before
# anyone can `package require Tk`. Explicit and early on purpose — a
# tclkit that carries a static core-fonts Tk registers its ifneeded at
# boot and would win the require, and a package once provided is final,
# so loading ours first IS the suppression. On a Tk-less tclkit the
# same load is simply the only Tk there is. tk_library must be told
# rather than searched for: Tk_Init runs off a nameless temp copy of
# the .so (the core's way of loading out of a VFS) and would go looking
# near paths that mean nothing here.
if {[catch {package present Tk}]} {
    set ::tk_library [file join $starkit::topdir lib tk9.0]
    load [file join $::tk_library libtcl9tk9.0.so] Tk
}
package require tk9wm
tk9wm-main {*}$argv
EOF

# sdx refuses to use as a prefix the runtime it is itself running from,
# so the starpack is built on a COPY — which also cuts the result loose
# from wherever the stock tclkit happens to live.
cp -f "$TCLKIT" "$HERE/runtime-tclkit"
chmod +w "$HERE/runtime-tclkit"

cd "$HERE"
rm -f tk9wm.kit tk9wm.bin
"$TCLKIT" "$SDX" wrap tk9wm.kit -vfs tk9wm.vfs
"$TCLKIT" "$SDX" wrap tk9wm.bin -vfs tk9wm.vfs -runtime "$HERE/runtime-tclkit"
chmod +x tk9wm.kit tk9wm.bin
ls -l tk9wm.kit tk9wm.bin
